apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: range-ip
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.225-192.168.2.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: range-ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - range-ip

