---
- name: Apply common configuration
  hosts: all
  become: true
  roles:
    - common

- name: Configure Kubernetes masters
  hosts: masters
  become: true
  roles:
    - master

- name: Configure Kubernetes nodes
  hosts: nodes
  become: true
  roles:
    - node
