all:
  children:
    masters:
      hosts:
        master1:
          ansible_host: 192.168.100.64
          ansible_user: tribix
          ansible_become: true
    nodes:
      hosts:
        node1:
          ansible_host: 192.168.100.65
          ansible_user: tribix
          ansible_become: true
